version: '3.8'

services:
  nl-to-sql-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nl-to-sql-app:latest
    container_name: nl-to-sql-app
    ports:
      - "8080:8080"
    volumes:
      - /content/drive/MyDrive/mistral7b_sql_model:/models
      - ./credentials.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - PROJECT_ID=${PROJECT_ID}
      - DEFAULT_DATASET=${DEFAULT_DATASET}
      - MODEL_PATH=/models
      - USE_CUDA=True
      - USE_BF16=True
      - DEBUG=True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  default:
    name: nl-to-sql-network